package com.richard.domain.racing.model

data class RacingDomainModel(
    val raceId: String,
    val raceName: String,
    val raceNumber: Int,
    val meetingId: String,
    val meetingName: String,
    val categoryId: String,
    val advertisedStartTime: Long,
    val distance: Int,
    val distanceId: String,
    val distanceName: String,
    val distanceShortName: String,
    val trackId: String,
    val trackName: String,
    val trackShortName: String,
    val weatherId: String,
    val weatherName: String,
    val weatherShortName: String,
    val raceComment: String,
    val venueId: String,
    val venueName: String,
    val venueState: String,
    val venueCountry: String,
)